services:
  auth_db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    ports:
      - "8001:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth:
    build:
      context: ./auth_lct
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth_db
    volumes:
      - auth:/app
      
  core:
    build:
      context: ./app_metro_service
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      DB_HOST: core_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: metro
    depends_on:
      - core_db
    volumes:
      - core:/app

  core_db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metro
    ports:
      - "8002:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
  core_db_data:
  core:
  auth:
