spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:8002/metro
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

graph:
  common: src/main/resources/configs/common_graph.json
  special: src/main/resources/configs/special_graph.json

time_allowance_category: src/main/resources/configs/statistic.json
station: src/main/resources/configs/station.json

uri:
  registration: http://localhost:8000/

keystore:
    path: src/main/resources/configs/keystore.p12
    password: metro
