
CREATE TABLE PASSENGERS (
    ID SERIAL PRIMARY KEY,
    LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    SURNAME_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN
);

CREATE TABLE EMPLOYEE (
    ID SERIAL PRIMARY KEY,
    LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    SURNAME_NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    WORK_ARIA VARCHAR(255) NOT NULL,
    SEX VARCHAR(50) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN
);

CREATE TABLE BIDS (
    ID SERIAL PRIMARY KEY,
    ID_PAS INT REFERENCES PASSENGERS(id),
    CREATED_DATE DATE NOT NULL,
    CREATED_TIME TIME NOT NULL,
    BID_DATE DATE NOT NULL,
    BID_TIME TIME NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    ID_ST1 INT NOT NULL,
    ID_ST2 INT NOT NULL,
    INSPECTOR_M INT NOT NULL,
    INSPECTOR_F INT NOT NULL,
    TIME_PREDICT TIME,
    TIME_START TIME,
    TIME_OVER TIME
);


--CREATE TABLE WORK_SCHEDULE (
--   START_DATE DATE NOT NULL,
--   END_DATE DATE NOT NULL,
--   ID_EMPLOYEE INT REFERENCES EMPLOYEE(ID),
--   START_WORK TIME NOT NULL,
--   END_WORK TIME NOT NULL
--);

CREATE TABLE WORK_WEEK_HOURS (
    ID_EMPLOYEE INT REFERENCES EMPLOYEE(ID),
    MON VARCHAR(255),
    TUE VARCHAR(255),
    WED VARCHAR(255),
    THU VARCHAR(255),
    FRI VARCHAR(255),
    SAT VARCHAR(255),
    SUN VARCHAR(255)
);

CREATE TABLE DINNER_WEEK_HOURS (
    ID_EMPLOYEE INT REFERENCES EMPLOYEE(ID),
    MON VARCHAR(255),
    TUE VARCHAR(255),
    WED VARCHAR(255),
    THU VARCHAR(255),
    FRI VARCHAR(255),
    SAT VARCHAR(255),
    SUN VARCHAR(255)
);

CREATE TABLE ASSIGNED_BIDS (
    ID_BID INT REFERENCES BIDS(ID),
    ID_EMPLOYEE INT REFERENCES EMPLOYEE(ID)
);
